### ISSUE TITLE
Fix TTY once logged in to instance

### ISSUE THREAD

**Issue by murich** [tknerr/vagrant-managed-servers#21]
Once ssh`ed to instance execute         

```
sed -i 's/Defaults    requiretty/#Defaults    requiretty/g' /etc/sudoers
```

Otherwise it may result to 
==> default: Rsyncing folder: /local/vagrant/managed/ => /vagrant
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p '/vagrant'

Stdout from the command:

Stderr from the command:

sudo: sorry, you must have a tty to run sudo

**Comment by Vanuan** [comment]
I tried this, but it stuck in "Rsyncing folder" phase

**Comment by Vanuan** [comment]
I fixed this by enabling sudo without password:

    % sudo   ALL=(ALL:ALL) NOPASSWD: ALL

This weakens security (if a server user has sudo permissions by mistake), but I couldn't find another way.
