### ISSUE TITLE
rsync__exclude items ignored

### ISSUE THREAD

**Issue by insprintorob** [tknerr/vagrant-managed-servers#24]
I noticed if you have an rsync shared folder set up and you specify items to exclude using rsync__exclude, those items are still synced over.

I took a quick look through https://github.com/tknerr/vagrant-managed-servers/blob/master/lib/vagrant-managed-servers/action/sync_folders.rb, I can't  see anywhere it checks for the rsync__exclude option?

It would be good to have this option so that you can exclude things like environment specific config files etc...

**Comment by tknerr** [comment]
fixed via #68
