### ISSUE TITLE
vagrant provision fails on Windows servers using winrm communicator when using --provider=managed

### ISSUE THREAD

**Issue by chrisbaldauf** [tknerr/vagrant-managed-servers#28]
I'm piloting vagrant-managed-servers for some of our deployment use cases. It works fantastically for linux servers (thanks!), but I've found at least one issue when running `vagrant provision` against a Windows 2008 R2 server using the winrm communicator. To be clear, this "guest" machine was not provisioned using Vagrant and was created by our IT team and is running on a VMWare ESX host using VMWare tools. I'm running vagrant from terminal on Mac OSX 10.9.5.

This may not be the primary use case that vagrant-managed-servers was built for, but I think I'm close and have an interest in getting this to work, so I'd be happy to help if you can give me some direction.

Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: "get-childitem C:\\"
  config.vm.box = "tknerr/managed-server-dummy"

  instances = ['myserver.mydomain.com']

  instances.each do |instance|
    config.vm.define "#{instance}" do |box|
      box.vm.communicator = :winrm
      box.winrm.username = "vagrant"
      box.winrm.password = "vagrant"
      box.vm.provider :managed do |managed, override|
        managed.server = instance
      end
    end
  end

end
```

The `up`, `status` and `destroy` commands appear to work well, and when I run them with the `--debug` command line option, I am able to verify that they are connecting and communicating over winrm (not ssh). 

When I run the `vagrant provision` command, I am prompted for the ssh user's password (I had installed cygwin/openssh on the machine as an alternate approach, but I'd ideally like to get to a winrm only solution.

Output 
```
> vagrant provision

==> mymachine.mydomain.com: high-level network configurations (`config.vm.network`). They
==> mymachine.mydomain.com: will be silently ignored.
==> mymachine.mydomain.com: Warning! The ManagedServers provider doesn't support any of the Vagrant
==> mymachine.mydomain.com: high-level network configurations (`config.vm.network`). They
==> mymachine.mydomain.com: will be silently ignored.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000102504f08>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001009795e0>
 INFO warden: Calling IN action: #<VagrantPlugins::ManagedServers::Action::IsReachable:0x000001009804f8>
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: managed
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: mymachine.mydomain.com
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
DEBUG winrmshell: Output: {:data=>[{:stdout=>"mymachine\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
 INFO warden: Calling OUT action: #<VagrantPlugins::ManagedServers::Action::IsReachable:0x000001009804f8>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x00000105333618>
 INFO warden: Calling IN action: #<Proc:0x000001053fafb0@/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Provision:0x000001053335a0>
 INFO provision: Ignoring sentinel check, forcing provision
 INFO provision: Checking provisioner sentinel file...
 INFO provision: Sentinel found! Not provisioning.
 INFO warden: Calling IN action: #<VagrantPlugins::ManagedServers::Action::SyncFolders:0x0000010536a0a0>
 INFO warden: Calling IN action: #<Proc:0x000001053bb518@/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x000001053bb518@/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO interface: info: Rsyncing folder: /Users/cbaldauf/dev/cbaldauf/vagrant-managed-servers/ => /vagrant
 INFO interface: info: ==> mymachine.mydomain.com: Rsyncing folder: /Users/cbaldauf/dev/cbaldauf/vagrant-managed-servers/ => /vagrant
==> mymachine.mydomain.com: Rsyncing folder: /Users/cbaldauf/dev/cbaldauf/vagrant-managed-servers/ => /vagrant
DEBUG winrmshell: powershell executing:
mkdir '/vagrant' -force
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
DEBUG winrmshell: Output: {:data=>[{:stdout=>"\r\n"}, {:stdout=>"\r\n"}, {:stdout=>"    Directory: C:\\\r\n\r\n\r\nMode                LastWriteTime     Length Name                              \r\n----                -------------     ------ ----                              \r\nd----         11/4/2014   1:00 PM            vagrant                           \r\n"}], :exitcode=>0}
 INFO subprocess: Starting process: ["/usr/bin/rsync", "--verbose", "--archive", "-z", "--exclude", ".vagrant/", "--exclude", "Vagrantfile", "-e", "ssh -p 22 -o StrictHostKeyChecking=no -i '/Users/cbaldauf/.vagrant.d/insecure_private_key'  ", "/Users/cbaldauf/dev/cbaldauf/vagrant-managed-servers/", "vagrant@mymachine.mydomain.com:/vagrant"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: 
                            ****USAGE WARNING****

This is a private computer system. This computer system, including all
related equipment, networks, and network devices (specifically including
Internet access) are provided only for authorized use. This computer system
may be monitored for all lawful purposes, including to ensure that its use
is authorized, for management of the system, to facilitate protection against
unauthorized access, and to verify security procedures, survivability, and
operational security. Monitoring includes active attacks by authorized entities
to test or verify the security of this system. During monitoring, information
may be examined, recorded, copied and used for authorized purposes. All
information, including personal information, placed or sent over this system
may be monitored.

Use of this computer system, authorized or unauthorized, constitutes consent
to monitoring of this system. Unauthorized use may subject you to criminal
prosecution. Evidence of unauthorized use collected during monitoring may be
used for administrative, criminal, or other adverse action. Use of this system
constitutes consent to monitoring for these purposes.


vagrant@mymachine.mydomain.com's password: 
```

At this point, it feels like a dead end to me, since I'd strongly prefer to communicate over a single protocol (ssh or winrm and I'm favoring winrm given the additional support that it has been getting lately).

Within my local copy of the vagrant-managed-servers gem, I was able to add a patch and get it to run the actual provisioning step successfully. 

/action/sync_folder.rb
```
module VagrantPlugins
  module ManagedServers
    module Action
      # This middleware uses `rsync` to sync the folders over to the
      # AWS instance.
      class SyncFolders
        include Vagrant::Util::ScopedHashOverride

        def initialize(app, env)
          @app    = app
          @logger = Log4r::Logger.new("vagrant_managed_servers::action::sync_folders")
        end

        def call(env)
+          return
          @app.call(env)

          ssh_info = env[:machine].ssh_info
```

Output (no debug)
```
> vagrant provision
==> mymachine.mydomain.com: Warning! The ManagedServers provider doesn't support any of the Vagrant
==> mymachine.mydomain.com: high-level network configurations (`config.vm.network`). They
==> mymachine.mydomain.com: will be silently ignored.
==> mymachine.mydomain.com: Running provisioner: shell...
    mymachine.mydomain.com: Running: inline PowerShell script
==> mymachine.mydomain.com:     Directory: C:\
==> mymachine.mydomain.com: 
==> mymachine.mydomain.com: 
==> mymachine.mydomain.com: Mode                LastWriteTime     Length Name                              
==> mymachine.mydomain.com: ----                -------------     ------ ----                              
==> mymachine.mydomain.com: d----         7/13/2009  11:20 PM            PerfLogs                          
==> mymachine.mydomain.com: d-r--         11/4/2014   4:47 PM            Program Files                     
==> mymachine.mydomain.com: d-r--         3/29/2011   4:50 PM            Program Files (x86)               
==> mymachine.mydomain.com: d----         11/5/2014  12:24 PM            temp                              
==> mymachine.mydomain.com: d----         11/5/2014  12:24 PM            tmp                               
==> mymachine.mydomain.com: d-r--         11/4/2014   4:41 PM            Users                             
==> mymachine.mydomain.com: d----         11/4/2014   1:00 PM            vagrant                           
==> mymachine.mydomain.com: d----        10/29/2014  12:03 PM            Windows              
```

This obviously isn't a proper solution, but it allowed me to prove to myself that I was able to use winrm for end-to-end provisioning, although my prototype only uses an inline powershell script - I may want/need the files to be synced to the remote machine to do any sort of real provisioning. I saw that there was an open ticket related to using the built in vagrant rsync functionality (https://github.com/tknerr/vagrant-managed-servers/issues/17).

I'd like to get your thoughts on this and perhaps some guidance on how you recommend I proceed. Again, I'm willing to put some time and effort into a solution that I can submit back, but appreciate your recommendation on the best approach.

**Comment by lonniev** [comment]
Do you guys have a README for how to get both the Windows guest and the non-Windows host (here Mac) properly configured so that "vagrant provision" can work with a Windows guest. In my case, I use chocolately on the guest to bring in Bitvise SSHd and vagrant-winrm-config. "vagrant ssh" works fine now. I tried throwing in cwRsync but the Mac rsync and the cwRsync don't agree to talk. Of course, I'd just like the known good configuration of Windows apps and vagrant settings that would allow this setup issue to go away.

**Comment by chrisbaldauf** [comment]
@lonniev, can you post the contents of your Vagrantfile? Maybe in a gist? I've been regularly spinning up and connecting to Windows machines from my Mac, so I'd be happy to take a look.

**Comment by lonniev** [comment]
Turns out it is a known issue in vagrant pre-1.7.3 about rsync and its inability (or decision) not to pre-create a nested directory structure. Rsynch is complaining that the destination directory for /tmp/vagrant-chef-#/ does not exist.

I borrowed some veewee and packer box-configuration scripts to come up with https://gist.github.com/lonniev/350a444c626119c31208 to get the Softlayer instance into a vagrant-talkative mood.

This all works except that the rsync/vagrant issue of pre-1.7.3 remains.

**Comment by lonniev** [comment]
I think I could probably swap out the cygwin ssh and rsync for the BitVise/cwRsync that I started with in the gist script and get right back to the same rsync issue. So, I will wait for 1.7.3.

**Comment by chrisbaldauf** [comment]
Is there a reason that you're not using the winrm communicator for Windows? 

http://docs.vagrantup.com/v2/vagrantfile/winrm_settings.html
http://www.vagrantup.com/blog/feature-preview-vagrant-1-6-windows.html

**Comment by lonniev** [comment]
The communicator for vagrant is set to winrm and the post install provisioning script does enable winrm and vagrant --debug does show that winrm is there and open.

The need is, apparently, for rsync and ssh to share local host directories with the guest OS to support the chef-solo provisioner. I would set the sync folder type to nfs or smb if the host/guest pair supported either. They don't.

**Comment by chrisbaldauf** [comment]
Ah, now I better understand. Yes, SMB host support on mac has been on my todo list for a while now - I just haven't gotten to it yet. What I've been doing as a workaround with winrm is to abandon the puppet provisioner (we use puppet, not chef), and just craft the appropriate `puppet apply --modulepath c:\vagrant\puppet\modules c:\vagrant\puppet\manifests\default.pp <extra_args>` command in a shell provisioner. 

Again, not ideal, but it has been working for us for the time being.

**Comment by lonniev** [comment]
Likewise, I comment out the chef-solo provisioner and manually choco-up the instance. Hopefully, one day, we'll all have a configuration that truly/fully supports Unixy hosts and Windows guests.

**Comment by lonniev** [comment]
just FYI as I expect vagrant 1.7.3 to fix this (and offer World Peace):

```bash
Host path: /Users/lonniev/Vagrants/softlayer-windows-integrity/cookbooks/
Guest path: /tmp/vagrant-chef/3c82aaf2d4fcab5d6e99f607c734158c/cookbooks
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/lonniev/.vagrant.d/insecure_private_key' --exclude .vagrant/ /Users/lonniev/Vagrants/softlayer-windows-integrity/cookbooks/ vagrant@75.126.3.66:/tmp/vagrant-chef/3c82aaf2d4fcab5d6e99f607c734158c/cookbooks
Error: Warning: Permanently added '75.126.3.66' (RSA) to the list of known hosts.
rsync: mkdir "/tmp/vagrant-chef/3c82aaf2d4fcab5d6e99f607c734158c/cookbooks" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]
```

It is the no such file or directory on the guest that is the problem.

**Comment by tknerr** [comment]
Thanks @chrisbaldauf for jumping in, I couldn't have helped with this!

@lonniev just curious as you mentioned softlayer (and that will probably not solve your problem), but did you try out https://github.com/audiolize/vagrant-softlayer? I did not, but would be interested in whether it's usable or not...

**Comment by lonniev** [comment]
@tknerr For SoftLayer images, I have crafted a custom post_install script to make a base SL Windows image communicative with vagrant.

The post installer installer is here:
https://gist.github.com/lonniev/7d967b09add6ca1f3a8a

**Comment by tknerr** [comment]
Thanks @lonniev, that is super useful!

**Comment by lonniev** [comment]
The problem with rsync is that it elects by design not to create missing parent directories in the path to the destination folder.

I could pre-create the complete path if I knew it a priori but it is constructed in the chef ruby code as it is needed. Therefore, with `/tmp/vagrant-chef/3c82aaf2d4fcab5d6e99f607c734158c/cookbooks`, I don't have the magic hash value `3c82...` beforehand.

**Comment by lonniev** [comment]
Returning to this after several months, still in need of a solution, I looked at the vagrant source code to learn a bit. I see that for Linux guests there is an rsync.rb Cap class that performs the crucial `"sudo mkdir -p #{opts[:guest_path]}"` operation for rsync. That "guest path" parameter is the pathname that I thought (back on April 21st) was unavailable to me.

There is no similar Cap file for Windows guests.

I will try "monkey patching" my vagrant installation (1.7.2) to see if I can wedge in this missing capability for Windows guests.

If someone knows a better way to accomplish this goal, just reply here.

**Comment by lonniev** [comment]
Evidently, the addition of the rsync_pre is absolutely the way this kind of issue is intended to be addressed: for, in fact, that is exactly what @mitchellh has done for the future vagrant 1.7.3. See his commit 56a6c85e7df482c922910c941c2dda7bfd1250c8 for the addition to latest vagrant.

**Comment by lonniev** [comment]
I found out that the setup for vagrant and chef on the target guest box was not completely correct: it had the TEMP environment variable set to c:\Windows\TEMP and a PATH file therein with that path stated. However, the chef provisioning rsyncs were attempting to copy into c:\tmp folders.

The quickest way to resolve these two paths to temporary folders was to delete c:\tmp and create a symlink of c:\tmp ontp c:\Windows\TEMP. Now, regardless of whether the code uses the environment variable, the PATH file clue, the explicit c:\Windows\TEMP path, the explicit c:\tmp path, or the implicit cygwin /tmp path, all paths lead to the same folder.

**Comment by tknerr** [comment]
@lonniev nice find! Sorry I can't help you much further with that... :-/
