### ISSUE TITLE
vagrant ssh -c COMMAND

### ISSUE THREAD

**Issue by warrenseine** [tknerr/vagrant-managed-servers#33]
The plugin seems to ignore the `-c` argument.

**Comment by tknerr** [comment]
Hi @warrenseine, thanks for reporting all these bugs!

I'm a bit busy this week, but I will have a look at it next week. In the meantime, if you feel you can help out with a pull request on a few of the issues, that would be awesome too. In any case they should be taken care of...

**Comment by tknerr** [comment]
@warrenseine can you provide an example? It seems to work for me, e.g. here (please ignore the warning, I will have to look into that too):
```
C:\Repos\_github\vagrant-managed-servers>vagrant ssh my_server -c "pwd"
==> my_server: The machine is backed by a cloud provider (managed), caching
==> my_server: will be disabled.
==> my_server: Warning! The ManagedServers provider doesn't support any of the Vagrant
==> my_server: high-level network configurations (`config.vm.network`). They
==> my_server: will be silently ignored.
/home/vagrant
Connection to 192.168.40.35 closed.
```

**Comment by tknerr** [comment]
btw: network warning is gone as of https://github.com/tknerr/vagrant-managed-servers/pull/37

**Comment by tknerr** [comment]
@warrenseine can you verify this works for you too?

**Comment by warrenseine** [comment]
It does seem to work.

I think the initial bug I had was related to the confusion between hosts when not specifying the machine.
