### ISSUE TITLE
"vagrant rsync" and "vagrant rsync-auto" not working with managed provider

### ISSUE THREAD

**Issue by rivaros** [tknerr/vagrant-managed-servers#52]
These 2 very useful vagrant commands do not work in "managed" provider.
When running them they just exit silently. 

While with other providers like "virtualbox" evrth works ok.
Using vagrant 1.7.4

Could you investigate this issue?

**Comment by rivaros** [comment]
Additional info: Seems like plugin is not creating the synced_folders file in .vagrant\machines\{name of managed machine}\managed\synced_folders

I created the file based on the real vagrant box, and

"vagrant rsync" started to work.
So it analizes this file.

"vagrant rscync-auto" still does not work

**Comment by tknerr** [comment]
Hi @rivaros, thanks for reporting this! 

Yes, the `rsync` and `rsync-auto` options are not supported at the moment.

They would have to be added to [action.rb](https://github.com/tknerr/vagrant-managed-servers/blob/master/lib/vagrant-managed-servers/action.rb) here, similar to the [ssh_run action](https://github.com/tknerr/vagrant-managed-servers/blob/master/lib/vagrant-managed-servers/action.rb#L112-L132). Should not be too hard to add, but I'm a bit out of time at the moment :-(

Pull requests always welcome! :-)

**Comment by rivaros** [comment]
@tknerr, unfortunately I am not a ruby developer :((

**Comment by rivaros** [comment]
Anybody can handle this ?

**Comment by narqo** [comment]
:+1: for the issue. 

@tknerr what do you think, is there a possibility for you to implement the feature?

**Comment by tknerr** [comment]
Sorry, can't give you an ETA on this, currently too busy with $DAYJOB :-/
Am 21.01.2016 2:15 nachm. schrieb "Vladimir Varankin" <
notifications@github.com>:

**Comment by tknerr** [comment]
fixed via #68
