### ISSUE TITLE
vagrant-managed-servers/lib/vagrant-managed-servers/action/sync_folders.rb  : rsync wont delete content from the remote host during a provision.( stale files )

### ISSUE THREAD

**Issue by stephencooke** [tknerr/vagrant-managed-servers#61]
vagrant-managed-servers/lib/vagrant-managed-servers/action/sync_folders.rb  : rsync wont delete content from the remote host during a provision.( stale files )

Impact can be a broken service, if older versions of files are still delivered.   
I first saw this when puppet apache modsecurity changed and it left the old files in place, this caused apache to fail with a duplicate rule issue.

            command = [
              "rsync", "--verbose", "--archive", "-z",
              "--exclude", ".vagrant/", "--exclude", "Vagrantfile",
              "-e", "ssh -l '#{ssh_info[:username]}' -p #{ssh_info[:port]} -o StrictHostKeyChecking=no #{ssh_key_options} #{ssh_proxy_commands}",
              hostpath,
              "#{ssh_info[:host]}:#{guestpath}"]

The above is missing an option ( delete ), this causes files never to be deleted, this can cause issues with deployments.
rsync has a few options for this, having one of them available would be good, ideally having the  --delete-during as default would be nice.

     --del                   an alias for --delete-during
     --delete                delete extraneous files from destination dirs
     --delete-before         receiver deletes before transfer, not during
     --delete-during         receiver deletes during the transfer
     --delete-delay          find deletions during, delete after
 
if this is duplicate, then please close it. I couldnt see anyone mentioning this before( which suprised me)

**Comment by tknerr** [comment]
@stephencooke wow, indeed, this is quite a bug... have not used the plugin for a while, and wanted to test it with the latest vagrant version anyway.  Adding the `--del` option sounds sensible.

**Comment by stephencooke** [comment]
We are using mainly Centos based connections, so can offer feedback on issues quiet quickly.

it is currently used to ssh manage  real machines , libvirt, rackspace and vboxes

**Comment by promethe42** [comment]
+1 this is a big problem for me too.
I'm using KeystoneJS (http://keystonejs.com/) and some left-over model files are accounted for even if I deleted them from my project. As a consequence, the CMS loads models that should not exist anymore.
When can we hope for this to be fixed?

**Comment by tknerr** [comment]
@promethe42 @stephencooke working on it now... sorry for the delay
